language: java
sudo: required

env:
  global:
    - MAVEN_OPTS="-Xmx512M"
    - PATH="$HOME/build/Lewuathe/docker-hadoop-cluster/apache-maven-3.5.2/bin:$PATH"

services:
  - docker

before_install:
  - docker info
  - git submodule update --init

install:
  - travis_wait make build

script:
  - cd ..
  - make

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push lewuathe/hadoop-base:latest;
    docker push lewuathe/hadoop-master:latest;
    docker push lewuathe/hadoop-slave:latest;
    fi
